import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en">
		<head>
			<meta charSet="UTF-8"/>
			<meta
				name="viewport"
				content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
			/>
			{/*<meta http-equiv="X-UA-Compatible" content="ie=edge"/>*/}
			<title>BankCo - Analytics</title>
			<link rel="stylesheet" href="/assets/css/slick.css"/>
			<link rel="stylesheet" href="/assets/css/aos.css"/>
			<link rel="stylesheet" href="/assets/css/flatpickr.min.css"/>
			<link rel="stylesheet" href="/assets/css/output.css"/>
			<link rel="stylesheet" href="/assets/css/style.css"/>
			<link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet"/>
			<link
				href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
				rel="stylesheet"
			/>
		</head>
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
		{children}

		<script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"
			defer
		></script>
		<script src="/assets/js/jquery-3.6.0.min.js"></script>
		<script src="/assets/js/flatpickr.js"></script>
		<script src="/assets/js/slick.min.js"></script>
		<script src="/assets/js/aos.js"></script>
		<script>
			AOS.init();
		</script>
		<script src="/assets/js/main.js"></script>
		<script src="/assets/js/chart.js"></script>
		</body>
		</html>);
}
